# Prática de transformação de dados com Pandas

In [3]:
import pandas as pd

In [5]:
compras = pd.read_excel("compras_loja_a.xlsx")

In [6]:
compras.shape

(46, 7)

A base possui valores duplicados?

In [7]:
compras.columns

Index(['Data', 'Região', 'Representante', 'Item', 'Unidade', 'Preço Unidade',
       'Total'],
      dtype='object')

In [8]:
compras.groupby(['Data', 'Região', 'Representante', \
                 'Item'])

In [9]:
compras.groupby(['Data', 'Região', 'Representante', \
                 'Item']).count()

                                       Unidade  Preço Unidade  Total
Data     Região Representante Item
1/2/19   Centro Smith         Caderno        1              1      1
1/4/18   Leste  Jones         Caderno        1              1      1
1/9/18   Centro Smith         Mesa           1              1      1
10/4/19  Centro Andrews       Lapis          1              1      1
10/9/19  Centro Gill          Lapis          1              1      1
12/12/18 Centro Smith         Lapis          1              1      1
12/7/18  Leste  Howard        Caderno        2              2      2
14/10/19 Oeste  Thompson      Caderno        1              1      1
14/5/19  Centro Gill          Lapis          1              1      1
15/1/19  Centro Gill          Caderno        1              1      1
15/3/18  Oeste  Sorvino       Lapis          1              1      1
15/8/18  Leste  Jones         Lapis          1              1      1
17/11/19 Centro Jardine       Caderno        1              1      1
18/2/19  Leste  Jones         Caderno        1              1      1
18/4/18  Centro Andrews       Lapis          1              1      1
18/9/18  Leste  Jones         Estojo         1              1      1
21/12/19 Centro Andrews       Caderno        0              0      0
21/7/19  Centro Morgan        Estojo         1              1      1
22/10/18 Leste  Jones         Pen            1              1      1
22/5/18  Oeste  Thompson      Lapis          1              1      1
23/1/18  Centro Kivell        Caderno        2              2      2
24/3/19  Centro Jardine       Estojo         1              1      1
24/8/19  Oeste  Sorvino       Mesa           1              1      1
25/11/18 Centro Kivell        Estojo         1              1      1
25/6/18  Centro Morgan        Lapis          2              2      2
26-2-/18 Centro Gill          Pen            1              1      1
27/4/19  Leste  Howard        Pen            1              1      1
27/9/19  Oeste  Sorvino       Pen            1              1      0
29/12/18 Leste  Parent        Estojo         1              1      1
29/7/18  Leste  Parent        Caderno        1              1      1
31/10/19 Centro Andrews       Lapis          1              0      1
31/5/19  Centro Gill          Caderno        1              1      0
4/12/19  Centro Jardine       Caderno        1              1      1
4/7/19   Leste  Jones         Estojo         1              1      1
5-5-18   Centro Jardine       Lapis          1              1      1
5/10/18  Centro Morgan        Caderno        1              1      1
6/1/18   Leste  Jones         Lapis          1              1      1
7/3/19   Oeste  Sorvino       Caderno        1              1      1
7/8/19   Centro Kivell        Estojo         1              1      1
8/11/18  Leste  Parent        Pen            1              1      1
8/6/18   Leste  Jones         Caderno        1              1      1
9/2/18   Centro Jardine       Lapis          1              1      1

Nesse caso se faz necessário excluir algumas linhas duplicadas

In [11]:
compras.shape

(46, 7)

In [13]:
compras = compras.drop_duplicates()

In [14]:
compras.shape

(43, 7)

A base possui valores ausentes?

In [15]:
compras.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43 entries, 0 to 45
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Data           43 non-null     object
 1   Região         43 non-null     object
 2   Representante  43 non-null     object
 3   Item           42 non-null     object
 4   Unidade        42 non-null     float64
 5   Preço Unidade  41 non-null     object
 6   Total          40 non-null     float64
dtypes: float64(2), object(5)
memory usage: 2.7+ KB

In [16]:
compras.isnull()

     Data  Região  Representante   Item  Unidade  Preço Unidade  Total
0   False   False          False  False    False          False  False
1   False   False          False  False    False          False  False
3   False   False          False  False    False          False  False
4   False   False          False  False    False          False  False
5   False   False          False  False    False          False  False
6   False   False          False  False    False          False  False
7   False   False          False  False    False          False  False
8   False   False          False  False    False          False  False
9   False   False          False  False    False          False  False
10  False   False          False  False    False          False  False
11  False   False          False  False    False          False  False
12  False   False          False  False    False          False  False
15  False   False          False  False    False          False  False
16  False   False          False  False    False          False  False
17  False   False          False  False    False          False  False
18  False   False          False  False    False          False  False
19  False   False          False  False    False          False  False
20  False   False          False  False    False          False  False
21  False   False          False  False    False          False  False
22  False   False          False  False    False          False  False
23  False   False          False  False    False          False  False
24  False   False          False  False    False          False  False
25  False   False          False  False    False          False  False
26  False   False          False  False    False          False  False
27  False   False          False  False    False          False  False
28  False   False          False  False    False          False  False
29  False   False          False  False    False          False  False
30  False   False          False  False    False          False  False
31  False   False          False  False    False          False  False
32  False   False          False  False    False          False  False
33  False   False          False  False    False          False   True
34  False   False          False   True    False          False  False
35  False   False          False  False    False          False  False
36  False   False          False  False    False          False  False
37  False   False          False  False    False          False  False
38  False   False          False  False    False          False  False
39  False   False          False  False    False          False  False
40  False   False          False  False    False          False   True
41  False   False          False  False    False          False  False
42  False   False          False  False    False           True  False
43  False   False          False  False    False          False  False
44  False   False          False  False    False          False  False
45  False   False          False  False     True           True   True

In [17]:
compras.isnull().any()

Data             False
Região           False
Representante    False
Item              True
Unidade           True
Preço Unidade     True
Total             True
dtype: bool

In [18]:
compras.isnull().any(axis=1)

0     False
1     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33     True
34     True
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42     True
43    False
44    False
45     True
dtype: bool

In [19]:
compras[compras.isnull().any(axis=1)]

        Data  Região Representante     Item  Unidade Preço Unidade   Total
33   31/5/19  Centro          Gill  Caderno     80.0          8.99     NaN
34   17/6/19  Centro        Kivell      NaN      5.0           125  625.00
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99     NaN
42  31/10/19  Centro       Andrews    Lapis     14.0           NaN   18.06
45  21/12/19  Centro       Andrews  Caderno      NaN           NaN     NaN

Quando entramos com este comando, o python exibe somente as linhas onde faltam os dados. É necessário entender a importância do dado para nosso projeto para definir qual será o destino do dado.

Vejamos agora como excluir uma linha dentro do dataframe

In [21]:
compras = compras.drop(45)

In [22]:
compras.drop(34, inplace= True)

In [23]:
compras

        Data  Região Representante     Item  Unidade Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99   179.64
4   26-2-/18  Centro          Gill      Pen     27.0         19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99   149.25
8     5-5-18  Centro       Jardine    Lapis     90.0          4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0          4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0          1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0         19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0          4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0           125   250.00
18   18/9/18   Leste         Jones   Estojo     16.0         15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0          8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0          8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0         19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0          4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0          1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0         15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0          8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0            15  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0          4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0         19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0          4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0          1;99   131.34
31   27/4/19   Leste        Howard      Pen     96.0          4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0          1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0          8.99      NaN
35    4/7/19   Leste         Jones   Estojo     62.0          4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0         12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0         23;95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0           275   825.00
39   10/9/19  Centro          Gill    Lapis      7.0          1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99      NaN
41  14/10/19   Oeste      Thompson  Caderno     57.0         19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0           NaN    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0          4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0         19.99  1879.06

In [24]:
compras[compras.isnull().any(axis=1)]

        Data  Região Representante     Item  Unidade Preço Unidade  Total
33   31/5/19  Centro          Gill  Caderno     80.0          8.99    NaN
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99    NaN
42  31/10/19  Centro       Andrews    Lapis     14.0           NaN  18.06

Neste caso acima observa-se que o problema da coluna com dado nulo é um problema de operação, e assim , podemos realizar a operação e preencher o dado faltante

In [28]:
compras.loc[33, "Total"] = compras.loc[33, "Unidade"] *compras.loc[33,"Preço Unidade"]

In [29]:
compras

        Data  Região Representante     Item  Unidade Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99   179.64
4   26-2-/18  Centro          Gill      Pen     27.0         19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99   149.25
8     5-5-18  Centro       Jardine    Lapis     90.0          4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0          4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0          1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0         19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0          4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0           125   250.00
18   18/9/18   Leste         Jones   Estojo     16.0         15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0          8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0          8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0         19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0          4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0          1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0         15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0          8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0            15  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0          4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0         19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0          4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0          1;99   131.34
31   27/4/19   Leste        Howard      Pen     96.0          4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0          1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0          8.99   719.20
35    4/7/19   Leste         Jones   Estojo     62.0          4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0         12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0         23;95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0           275   825.00
39   10/9/19  Centro          Gill    Lapis      7.0          1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99      NaN
41  14/10/19   Oeste      Thompson  Caderno     57.0         19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0           NaN    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0          4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0         19.99  1879.06

In [30]:
compras.loc[40, "Total"] = compras.loc[40, "Unidade"] *compras.loc[40,"Preço Unidade"]

In [31]:
compras

        Data  Região Representante     Item  Unidade Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99   179.64
4   26-2-/18  Centro          Gill      Pen     27.0         19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99   149.25
8     5-5-18  Centro       Jardine    Lapis     90.0          4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0          4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0          1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0         19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0          4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0           125   250.00
18   18/9/18   Leste         Jones   Estojo     16.0         15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0          8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0          8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0         19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0          4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0          1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0         15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0          8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0            15  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0          4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0         19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0          4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0          1;99   131.34
31   27/4/19   Leste        Howard      Pen     96.0          4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0          1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0          8.99   719.20
35    4/7/19   Leste         Jones   Estojo     62.0          4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0         12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0         23;95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0           275   825.00
39   10/9/19  Centro          Gill    Lapis      7.0          1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99   151.24
41  14/10/19   Oeste      Thompson  Caderno     57.0         19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0           NaN    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0          4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0         19.99  1879.06

In [34]:
compras.loc[42, "Preço Unidade"] = compras.loc[42, "Total"] /compras.loc[42,"Unidade"]

In [35]:
compras

        Data  Região Representante     Item  Unidade Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99   179.64
4   26-2-/18  Centro          Gill      Pen     27.0         19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99   149.25
8     5-5-18  Centro       Jardine    Lapis     90.0          4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0          4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0          1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0         19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0          4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0           125   250.00
18   18/9/18   Leste         Jones   Estojo     16.0         15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0          8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0          8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0         19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0          4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0          1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0         15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0          8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0            15  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0          4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0         19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0          4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0          1;99   131.34
31   27/4/19   Leste        Howard      Pen     96.0          4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0          1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0          8.99   719.20
35    4/7/19   Leste         Jones   Estojo     62.0          4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0         12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0         23;95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0           275   825.00
39   10/9/19  Centro          Gill    Lapis      7.0          1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99   151.24
41  14/10/19   Oeste      Thompson  Caderno     57.0         19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0          1.29    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0          4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0         19.99  1879.06

In [36]:
compras[compras.isnull().any(axis=1)]

Empty DataFrame
Columns: [Data, Região, Representante, Item, Unidade, Preço Unidade, Total]
Index: []

A base tem formatação diferente?

In [37]:
compras.head(10)

        Data  Região Representante     Item  Unidade Preço Unidade   Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99  189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99  999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99  179.64
4   26-2-/18  Centro          Gill      Pen     27.0         19.99  539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99  167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99  299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99  149.25
8     5-5-18  Centro       Jardine    Lapis     90.0          4.99  449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99   63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99  539.40

diferença na formatação da data que pode dar problema posterior

In [39]:
compras.Data = compras.Data.str.replace("-","/")

In [40]:
compras.Data = compras.Data.str.replace("//" , "/")

In [41]:
compras

        Data  Região Representante     Item  Unidade Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0          1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0         19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0          4.99   179.64
4    26/2/18  Centro          Gill      Pen     27.0         19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0          2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0          4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0          1.99   149.25
8     5/5/18  Centro       Jardine    Lapis     90.0          4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0          1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0          8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0          4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0          1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0         19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0          4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0           125   250.00
18   18/9/18   Leste         Jones   Estojo     16.0         15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0          8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0          8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0         19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0          4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0          1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0         15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0          8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0            15  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0          4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0         19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0          4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0          1;99   131.34
31   27/4/19   Leste        Howard      Pen     96.0          4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0          1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0          8.99   719.20
35    4/7/19   Leste         Jones   Estojo     62.0          4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0         12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0         23;95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0           275   825.00
39   10/9/19  Centro          Gill    Lapis      7.0          1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0          1.99   151.24
41  14/10/19   Oeste      Thompson  Caderno     57.0         19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0          1.29    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0          4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0         19.99  1879.06

In [46]:
preco_ajustado =[]
for preco in compras ["Preço Unidade"]:
    preco_ajustado.append(float(str(preco).replace(";" , ".")))

In [47]:
compras["Preço Unidade"] = preco_ajustado

In [48]:
compras

        Data  Região Representante     Item  Unidade  Preço Unidade    Total
0     6/1/18   Leste         Jones    Lapis     95.0           1.99   189.05
1    23/1/18  Centro        Kivell  Caderno     50.0          19.99   999.50
3     9/2/18  Centro       Jardine    Lapis     36.0           4.99   179.64
4    26/2/18  Centro          Gill      Pen     27.0          19.99   539.73
5    15/3/18   Oeste       Sorvino    Lapis     56.0           2.99   167.44
6     1/4/18   Leste         Jones  Caderno     60.0           4.99   299.40
7    18/4/18  Centro       Andrews    Lapis     75.0           1.99   149.25
8     5/5/18  Centro       Jardine    Lapis     90.0           4.99   449.10
9    22/5/18   Oeste      Thompson    Lapis     32.0           1.99    63.68
10    8/6/18   Leste         Jones  Caderno     60.0           8.99   539.40
11   25/6/18  Centro        Morgan    Lapis     90.0           4.99   449.10
12   12/7/18   Leste        Howard  Caderno     29.0           1.99    57.71
15   29/7/18   Leste        Parent  Caderno     81.0          19.99  1619.19
16   15/8/18   Leste         Jones    Lapis     35.0           4.99   174.65
17    1/9/18  Centro         Smith     Mesa      2.0         125.00   250.00
18   18/9/18   Leste         Jones   Estojo     16.0          15.99   255.84
19   5/10/18  Centro        Morgan  Caderno     28.0           8.99   251.72
20  22/10/18   Leste         Jones      Pen     64.0           8.99   575.36
21   8/11/18   Leste        Parent      Pen     15.0          19.99   299.85
22  25/11/18  Centro        Kivell   Estojo     96.0           4.99   479.04
23  12/12/18  Centro         Smith    Lapis     67.0           1.29    86.43
24  29/12/18   Leste        Parent   Estojo     74.0          15.99  1183.26
25   15/1/19  Centro          Gill  Caderno     46.0           8.99   413.54
26    1/2/19  Centro         Smith  Caderno     87.0          15.00  1305.00
27   18/2/19   Leste         Jones  Caderno      4.0           4.99    19.96
28    7/3/19   Oeste       Sorvino  Caderno      7.0          19.99   139.93
29   24/3/19  Centro       Jardine   Estojo     50.0           4.99   249.50
30   10/4/19  Centro       Andrews    Lapis     66.0           1.99   131.34
31   27/4/19   Leste        Howard      Pen     96.0           4.99   479.04
32   14/5/19  Centro          Gill    Lapis     53.0           1.29    68.37
33   31/5/19  Centro          Gill  Caderno     80.0           8.99   719.20
35    4/7/19   Leste         Jones   Estojo     62.0           4.99   309.38
36   21/7/19  Centro        Morgan   Estojo     55.0          12.49   686.95
37    7/8/19  Centro        Kivell   Estojo     42.0          23.95  1005.90
38   24/8/19   Oeste       Sorvino     Mesa      3.0         275.00   825.00
39   10/9/19  Centro          Gill    Lapis      7.0           1.29     9.03
40   27/9/19   Oeste       Sorvino      Pen     76.0           1.99   151.24
41  14/10/19   Oeste      Thompson  Caderno     57.0          19.99  1139.43
42  31/10/19  Centro       Andrews    Lapis     14.0           1.29    18.06
43  17/11/19  Centro       Jardine  Caderno     11.0           4.99    54.89
44   4/12/19  Centro       Jardine  Caderno     94.0          19.99  1879.06

In [49]:
compras.isnull().sum()

Data             0
Região           0
Representante    0
Item             0
Unidade          0
Preço Unidade    0
Total            0
dtype: int64

In [50]:
compras.describe()

         Unidade  Preço Unidade        Total
count  41.000000      41.000000    41.000000
mean   50.926829      18.128780   460.077073
std    29.779515      45.485097   454.520121
min     2.000000       1.290000     9.030000
25%    28.000000       2.990000   149.250000
50%    55.000000       4.990000   299.400000
75%    75.000000      15.990000   575.360000
max    96.000000     275.000000  1879.060000